Update security advisories with recently assigned CVE IDs
bitcoin-core/bitcoincore.org pull request #1086
Opened 2024-11-18 21:01 UTC by darosior

Only the `inv-to-send` advisory doesn't have one because there is a misunderstanding who claims it should be `CVE-2023-33297`. I explained it is an ID which was claimed by a troll on behalf of the project and i'm now awaiting their response. I don't think it should be a blocker to publish the other 13 IDs.

2024-11-20 20:01 UTC, murchandamus commented on _posts/en/posts/2024-07-03-disclose-bip70-crash.md
> +title: Disclosure of CVE-2024-52918
I would also prefer if the titles continued to contain the gist of the vulnerability as the CVE ID provides zero context unless you know about the CVE in advance.

2024-11-20 20:06 UTC, murchandamus requested changes
This approach reduces the information content of the titles and I would consider it a disimprovement.

How about replacing the word "Disclosure" with the CVE ID? E.g.

```diff
-title: Disclosure of crash using malicious BIP72 URI
+title: CVE-2024-52918: Crash using malicious BIP72 URI
```

2025-01-31 17:17 UTC, BrunoSampaioDev commented on _posts/en/posts/2024-07-03-disclose-bip70-crash.md
> +title: Disclosure of CVE-2024-52918
I also agree that the CVE ID does not provide any context, I believe that titles containing the essence of the vulnerability are more useful

2025-02-21 18:28 UTC, darosior commented on _posts/en/posts/2024-07-03-disclose-bip70-crash.md
> +title: Disclosure of CVE-2024-52918
Done.

2025-02-21 18:51 UTC, darosior commented
Struggled with YAML but this should be good now. Took Mark's suggestion.

2025-02-21 19:15 UTC, murchandamus approved these changes

2025-02-21 20:27 UTC, 0xB10C commented
Might need to escape the `:` (`\:`) ?

2025-02-23 13:01 UTC, darosior commented
Tried a few things but now just ended up dropping the colons altogether and using `-` in place.

2025-02-23 13:25 UTC, darosior reviewed
Since it's been a while i went through all the CVE ids and re-checked they matched the disclosure.

2025-02-24 00:06 UTC, Zero-1729 approved these changes
ACK LGTM

2025-02-25 14:36 UTC, merged