Bitcoin Core 0.21.2
bitcoin-core/bitcoincore.org pull request #808
Opened 2021-09-29 07:17 UTC by fanquake

Adds a release announcement for 0.21.2. Modeled after #792.

2021-09-29 10:41 UTC, laanwj commented
Thanks! I think you got everything right, including the magnet link.

ACK 850d30d5f68207993d060da3bc5e485825fd9e82

2021-10-04 04:17 UTC, harding requested changes

2021-10-04 04:17 UTC, harding commented on _releases/0.21.2.md
> +[Transifex](https://www.transifex.com/bitcoin/bitcoin/).
Needs an additional line with `{% endgithubify %}` Example: https://github.com/bitcoin-core/bitcoincore.org/pull/792/files#diff-0bbaa9abb1d385dad9ae6fe573deb1f53269e1ef5daf9f024e95b2f7048fb2ccR1191

2021-10-04 04:17 UTC, harding commented on _releases/0.21.2.md
> +- #277 Do not use QClipboard::Selection on Windows and macOS. (hebasto)
The GUI PRs need to be prefixed with `gui`, e.g.

```text
- gui#277 Do not use QClipboard::Selection on Windows and macOS. (hebasto)
```

That way the automatic PR links will point to the correct repo.

2021-10-04 04:26 UTC, harding commented
Tested ACK a2820805aed231e1aec39aad7239d17a050c81d4 .  Checked local preview and locally ran the CI tests.  Thanks!

2021-10-04 04:26 UTC, harding approved these changes

2021-10-04 04:27 UTC, merged