Add portuguese translation of 0.21.2
bitcoin-core/bitcoincore.org pull request #864
Opened 2022-02-19 21:50 UTC by mateusnds

Hello everyone, I intend to help translate bitcoincore to Portuguese, I'm starting with this file to see if everything goes well.

Use this page to open Pull requests for changes to the Bitcoin Core project
website at [bitcoincore.org](https://bitcoincore.org).

[bitcoin.org](https://bitcoin.org) is not connected with or maintained by the
Bitcoin Core project contributors. Pull requests for changes to that website
should be opened at [the bitcoin.org
repository](https://github.com/bitcoin-dot-org/bitcoin.org/pulls).

General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com.

2022-02-21 21:06 UTC, katesalazar commented
will review

On Sat, Feb 19, 2022 at 10:51 PM bitmateus ***@***.***> wrote:

> Hello everyone, I intend to help translate bitcoincore to Portuguese, I'm
> starting with this file to see if everything goes well.
>
> Use this page to open Pull requests for changes to the Bitcoin Core project
> website at bitcoincore.org.
>
> bitcoin.org is not connected with or maintained by the
> Bitcoin Core project contributors. Pull requests for changes to that
> website
> should be opened at the bitcoin.org
> repository <https://github.com/bitcoin-dot-org/bitcoin.org/pulls>.
>
> General bitcoin questions and/or support requests are best directed to the
> Bitcoin StackExchange at https://bitcoin.stackexchange.com.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/bitcoin-core/bitcoincore.org/pull/864
> Commit Summary
>
>    - 9be1b2e
>    <https://github.com/bitcoin-core/bitcoincore.org/pull/864/commits/9be1b2ebce8333981a86a191de3babb603be78db>
>    Add portuguese translation of 0.21.2
>
> File Changes
>
> (1 file <https://github.com/bitcoin-core/bitcoincore.org/pull/864/files>)
>
>    - *A* _posts/pt_BR/posts/2021-09-13-release-22.0.md
>    <https://github.com/bitcoin-core/bitcoincore.org/pull/864/files#diff-9a33f3ac623cc56b97e3712f0f345c99677417f05ce02b5078998f9c476b8b5f>
>    (33)
>
> Patch Links:
>
>    - https://github.com/bitcoin-core/bitcoincore.org/pull/864.patch
>    - https://github.com/bitcoin-core/bitcoincore.org/pull/864.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoin-core/bitcoincore.org/pull/864>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMRS4W5NLEGUBJUBO4FGI2LU4AGFZANCNFSM5O3P4FMA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-02-22 19:59 UTC, katesalazar commented
missing the language name

---
<img width="920" alt="Screen Shot 2022-02-22 at 20 55 00" src="https://user-images.githubusercontent.com/52637275/155208824-41e4e494-6914-4907-b810-274838a12bc1.png">

---

2022-02-22 19:59 UTC, katesalazar commented on _posts/pt_BR/posts/2021-09-13-release-22.0.md
> +A versão 0.21.2 do Bitcoin Core está disponível para
nit: extra whitespace here

2022-02-22 20:00 UTC, katesalazar commented on _posts/pt_BR/posts/2021-09-13-release-22.0.md
> +[download][download page]. Veja as [notas de atualização][release
'baixar' instead of 'download'?

2022-02-22 20:03 UTC, katesalazar requested changes
- inconsistent name and content?
- lang name missing in the selector
- not passing ci

2022-02-22 20:03 UTC, katesalazar commented on _posts/pt_BR/posts/2021-09-13-release-22.0.md
> +id: pt-BR-blog-release-0.21.2
not matching the document name (...-22.0.md)

2022-10-21 07:47 UTC, fanquake commented
Please consolidate your changes into a single PR. i.e #905. Rather than opening many different ones.

2022-10-21 07:47 UTC, closed without merging