Adding pt-BR/rss
bitcoin-core/bitcoincore.org pull request #907
Opened 2022-10-20 15:17 UTC by mateusnds

When translating pages into Portuguese, I get an error saying that there is no rss in Portuguese, so I'm trying to create to follow the page translations

https://github.com/bitcoin-core/bitcoincore.org/pull/905 https://github.com/bitcoin-core/bitcoincore.org/pull/906

Ref:
***
  *  internally linking to /pt-BR/rss/, which does not exist (line 197) <a href="/pt-BR/rss/">RSS <img src="/assets/images/rss-24x24.png" alt="rss feeds" width="14" height="14"></a> htmlproofer 3.14.1 | Error:  HTML-Proofer found 1 failure! make: *** [Makefile:15: test-slow] Error 1
***

Use this page to open Pull requests for changes to the Bitcoin Core project
website at [bitcoincore.org](https://bitcoincore.org).

[bitcoin.org](https://bitcoin.org) is not connected with or maintained by the
Bitcoin Core project contributors. Pull requests for changes to that website
should be opened at [the bitcoin.org
repository](https://github.com/bitcoin-dot-org/bitcoin.org/pulls).

General bitcoin questions and/or support requests are best directed to the
Bitcoin StackExchange at https://bitcoin.stackexchange.com.

2022-10-20 15:35 UTC, mateusnds commented
:(

what image?

2022-10-20 18:12 UTC, katesalazar commented
> what image?

>  *  image /assets/images/rss-24x24.png does not have an alt attribute (line 169)
>  *  image /assets/images/rss-24x24.png does not have an alt attribute (line 173)

Maybe it's related to t.rss_feed in:
https://github.com/bitcoin-core/bitcoincore.org/blob/dc06536f6d16d0407cb09c6a15787d01dd974a1c/_includes/pages/rss.html#L3
and:
https://github.com/bitcoin-core/bitcoincore.org/blob/dc06536f6d16d0407cb09c6a15787d01dd974a1c/_includes/pages/rss.html#L7

note:
https://github.com/bitcoin-core/bitcoincore.org/blob/dc06536f6d16d0407cb09c6a15787d01dd974a1c/_data/translations.yml#L11
and:
https://github.com/bitcoin-core/bitcoincore.org/blob/dc06536f6d16d0407cb09c6a15787d01dd974a1c/_data/translations.yml#L25
and:
https://github.com/bitcoin-core/bitcoincore.org/blob/dc06536f6d16d0407cb09c6a15787d01dd974a1c/_data/translations.yml#L39
and:
https://github.com/bitcoin-core/bitcoincore.org/blob/dc06536f6d16d0407cb09c6a15787d01dd974a1c/_data/translations.yml#L53
and:
https://github.com/bitcoin-core/bitcoincore.org/blob/dc06536f6d16d0407cb09c6a15787d01dd974a1c/_data/translations.yml#L67

2022-10-20 18:14 UTC, katesalazar requested changes
currently failing CI, maybe able to be fixed by adding missing translations

2022-10-20 18:14 UTC, katesalazar commented on _posts/pt-BR/pages/2016-03-21-rss.md
> +{% include pages/rss.html %}
I think this line includes a localized page that fails to pass tests as it references untranslated keys.

2022-10-21 07:47 UTC, fanquake commented
Please consolidate your changes into a single PR. i.e #905. Rather than opening many different ones.

2022-10-21 07:47 UTC, closed without merging