Builder keys
bitcoin-core/bitcoincore.org pull request #964
Opened 2023-05-09 15:31 UTC by pinheadmz

Closes #945 
Closes https://github.com/bitcoin-core/bitcoincore.org/pull/957 (included)
Closes https://github.com/bitcoin-core/bitcoincore.org/pull/807 (included)
Closes https://github.com/bitcoin-core/bitcoincore.org/pull/878

download + verify procedure tested on macOS and Linux. I will go through it again on Windows tonight and add one more commit for that.

2023-05-09 15:39 UTC, fanquake commented
```bash
## Check for broken Markdown reference-style links that are displayed in text unchanged, e.g. [broken][broken link]
! find _site/ -name '*.html' | xargs grep ']\[' | grep -v skip-test | grep .
## Ensure that no template strings leak through liquid rendering
! find _site/ -name '*.html' | xargs grep '\$(.*)'
_site/es/download/index.html:<p>Por ejemplo, dada la línea <a href="$(BUILDER_KEYS_TXT_URL)"><code> builder-keys/keys.txt</code></a> <code>$(EXAMPLE_BUILDERS_LINE)</code> podrías cargar esa clave usando este comando:</p>
_site/es/download/index.html:<p>Por ejemplo, dada la línea <a href="$(BUILDER_KEYS_TXT_URL)"><code> builder-keys/keys.txt</code></a> <code>$(EXAMPLE_BUILDERS_LINE)</code> podrías cargar esa clave usando este comando:</p>
_site/es/download/index.html:      <li><p>Sería recomendable que eligieras varias personas de esta lista que estimes confiables e importes sus claves según se indica arriba, o importes todas las claves según las instrucciones en el documento <a href="$(BUILDER_KEYS_URL)"><code>contrib/builder-key</code> README</a>. Después usarás sus claves para comprobar las firmas que atestiguan la validez de las checksums que usas para comprobar los programas binarios.
_site/es/download/index.html:<p>Por ejemplo, dada la línea <a href="$(BUILDER_KEYS_TXT_URL)"><code> builder-keys/keys.txt</code></a> <code>$(EXAMPLE_BUILDERS_LINE)</code> podrías cargar esa clave usando este comando:</p>
_site/es/download/index.html:      <li><p>Sería recomendable que eligieras varias personas de esta lista que estimes confiables e importes sus claves según se indica arriba, o importes todas las claves según las instrucciones en el documento <a href="$(BUILDER_KEYS_URL)"><code>contrib/builder-key</code> README</a>. Después usarás sus claves para comprobar las firmas que atestiguan la validez de las checksums que usas para comprobar los programas binarios.
make: *** [Makefile:23: test-fast] Error 1
```

2023-05-09 18:35 UTC, pinheadmz commented
Fixed build error by completing spanish translation (muchas gracias, @sr-gi !)

For quick review I built the download page (only) and hosted english and spanish:

https://thebitcoinblockclock.com/bitcoin/es-download

https://thebitcoinblockclock.com/bitcoin/en-download

2023-05-09 18:49 UTC, sr-gi requested changes

2023-05-09 18:49 UTC, sr-gi commented on _posts/es/pages/2017-01-01-download.md
> +  de los checksums que se proporcionan conjuntamente con los binarios del código.
For consistency with the rest of the text, this should read "las checksums" instead of "los checksums"

2023-05-09 18:49 UTC, sr-gi commented on _posts/es/pages/2017-01-01-download.md
> +  contribuidores en los que confias han firmado los checksums que se encuentran
Same here, `:s/las/los/`

2023-05-09 18:49 UTC, sr-gi commented on _posts/es/pages/2017-01-01-download.md
> +  GPG para cargar de forma local estas claves públicas. Encontrarás varias de las clases de
`:s/clases/claves/`

2023-05-09 20:34 UTC, merged

2023-05-10 11:25 UTC, pinheadmz commented
I followed the steps successfully on my windows machine last night. A few weird things about it though I don't if its this way for a reason or not:

> Ensure that the checksum produced by the command above matches one of
  the checksums listed in the checksums file you downloaded earlier.  We
  recommend that you check every character of the two checksums to
  ensure they match.

Manually verifying 64 characters? I'm no Windows expert but I think you can basically grep:

`type SHA256SUMS | findstr 4cc2fe2e2f5e6068ecbf922564f2356a5388e4d00d8f852062f589b9577a21de`

and the last one:

> C:\Program Files (x86)\GnuPG\bin\gpg.exe

This wasn't my path for gpg and actually I found on my machine at least I could just execute the command `gpg.exe` without a path and it would work.