Bitcoin Core 25.1
bitcoin-core/bitcoincore.org pull request #991
Opened 2023-10-09 15:11 UTC by fanquake

2023-10-09 17:21 UTC, katesalazar requested changes

2023-10-09 17:21 UTC, katesalazar commented on _posts/en/posts/2023-10-15-release-25.1.md
> +[release notes]: /en/releases/24.1/
24.1

2023-10-19 09:35 UTC, fanquake commented
Binaries are now available: https://bitcoincore.org/bin/bitcoin-core-25.1/.
Updated with the magnet URL.

2023-10-19 10:07 UTC, glozow reviewed
ACK ae5bd17

built preview, looks fine, text looks correct, links seem to work

2023-10-19 10:10 UTC, fanquake commented on _releases/25.1.md
> +date: 2023-10-16
Fixed.

2023-10-19 13:38 UTC, glozow reviewed
reACK b6650ed

2023-10-19 13:39 UTC, merged